### PR TITLE
Allow switching of an identity's preferred locale

### PR DESCRIPTION
**Pull request by rjkip**
Dep https://github.com/SURFnet/Stepup-Middleware/pull/81

### CODE REVIEW

**Comment by rjkip** [comment]
:bomb: @DRvanR

**Comment by rjkip** [comment]
:bell: @DRvanR

**Comment by rjkip** [comment]
Added a wee change.

**Comment by DRvanR** [comment]
As discussed, please move the form etc. to the stepup-bundle, not really something for an ApiClient[bundle] :wink:

**Comment by rjkip** [comment]
:sparkles: @DRvanR

**Comment by DRvanR** [comment]
:+1:

**Pull request merged**
